### ISSUE TITLE
Jekyll::Tags::IncludeTagError on Bundler?

### ISSUE THREAD

**Issue by luixxiul** [gjtorikian/jekyll-last-modified-at#35]
Hi there,

Would you please have a look at jekyll/jekyll/issues/3389?
``Jekyll::Tags::IncludeTagError`` on Bundler might be caused by this plugin.

Thanks!

**Comment by gjtorikian** [comment]
Until `3.0.0` is officially supported, I probably won't have time to investigate into this too deeply. Will keep the issue upon until then.

**Comment by tjkohli** [comment]
I'm having a similar issue -- not sure what it means, exactly (Ruby isn't my forte).
Here's the error (works fine without the plugin):

````
/path-to-project/_plugins/jekyll-last-modified-at-master/lib/jekyll-last-modified-at.rb:10:in `<module:LastModifiedAt>': cannot load such file -- jekyll-last-modified-at/generator (LoadError)
	from /path-to-project/_plugins/jekyll-last-modified-at-master/lib/jekyll-last-modified-at.rb:3:in `<module:Jekyll>'
	from /path-to-project/_plugins/jekyll-last-modified-at-master/lib/jekyll-last-modified-at.rb:2:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:75:in `block (2 levels) in require_plugin_files'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:74:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:74:in `block in require_plugin_files'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:73:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:73:in `require_plugin_files'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:18:in `conscientious_require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/site.rb:97:in `setup'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/site.rb:49:in `initialize'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:30:in `new'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:30:in `process'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/bin/jekyll:17:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
````
