### ISSUE TITLE
Travis build errors with jekyll 3.5+

### ISSUE THREAD

**Issue by jayvdb** [gjtorikian/jekyll-last-modified-at#55]
All tests are failing

https://travis-ci.org/jayvdb/jekyll-last-modified-at/builds/348084091
https://travis-ci.org/jayvdb/jekyll-last-modified-at/jobs/348077039

```ruby
  1) Jekyll::LastModifiedAt::Determinator knows the last modified date of the file in question
     Failure/Error:
       @site = Jekyll::Site.new(Jekyll.configuration({
         "source"      => @fixtures_path.to_s,
         "destination" => @dest.to_s,
         "plugins"     => @plugins_src
       }))
     
     NoMethodError:
       private method `select' called for #<String:0x0000000321b850>
     # ./vendor/bundle/ruby/2.1.0/gems/jekyll-3.7.3/lib/jekyll/plugin_manager.rb:31:in `require_gems'
     # ./vendor/bundle/ruby/2.1.0/gems/jekyll-3.7.3/lib/jekyll/plugin_manager.rb:22:in `conscientious_require'
     # ./vendor/bundle/ruby/2.1.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:113:in `setup'
     # ./vendor/bundle/ruby/2.1.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:34:in `initialize'
     # ./spec/spec_helper.rb:40:in `new'
     # ./spec/spec_helper.rb:40:in `block (2 levels) in <top (required)>'
```

**Comment by jayvdb** [comment]
The reason for this is incompatibility with jekyll 3.5

**Comment by jayvdb** [comment]
Pinning jekyll works https://travis-ci.org/jayvdb/jekyll-last-modified-at/builds/348131352

But that isnt really a solution.

**Comment by inetbiz** [comment]
@jayvdb I cannot even get the gem installed. https://travis-ci.com/inetbiz/semantic-seo-jekyll/builds/108496490
